apiVersion: apps/v1
kind: Deployment
metadata:
  annotations: {}
  labels:
    olm.deployment-spec-hash: 54b4d949f8
    olm.owner: postgresoperator.v5.7.0
    olm.owner.kind: ClusterServiceVersion
    olm.owner.namespace: p2
    operators.coreos.com/crunchy-postgres-operator.p2: ""
  name: pgo
  ownerReferences:
  - apiVersion: operators.coreos.com/v1alpha1
    blockOwnerDeletion: false
    controller: false
    kind: ClusterServiceVersion
    name: postgresoperator.v5.7.0
    uid: eaddaa29-e2ae-4b95-94b6-45d65cc50655
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 1
  selector:
    matchLabels:
      postgres-operator.crunchydata.com/control-plane: postgres-operator
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        alm-examples: |-
          [
            {
              "apiVersion": "postgres-operator.crunchydata.com/v1beta1",
              "kind": "CrunchyBridgeCluster",
              "metadata": {
                "name": "example-crunchybridgecluster"
              },
              "spec": {
                "clusterName": "example-bridge-cluster",
                "isHa": false,
                "majorVersion": 16,
                "plan": "standard-4",
                "provider": "aws",
                "region": "us-west-2",
                "secret": "crunchy-bridge-api-key",
                "storage": "10Gi"
              }
            },
            {
              "apiVersion": "postgres-operator.crunchydata.com/v1beta1",
              "kind": "PGAdmin",
              "metadata": {
                "name": "example-pgadmin",
                "namespace": "openshift-operators"
              },
              "spec": {
                "dataVolumeClaimSpec": {
                  "accessModes": [
                    "ReadWriteOnce"
                  ],
                  "resources": {
                    "requests": {
                      "storage": "1Gi"
                    }
                  }
                },
                "serverGroups": [
                  {
                    "name": "Crunchy Postgres for Kubernetes",
                    "postgresClusterSelector": {}
                  }
                ]
              }
            },
            {
              "apiVersion": "postgres-operator.crunchydata.com/v1beta1",
              "kind": "PGUpgrade",
              "metadata": {
                "name": "example-upgrade"
              },
              "spec": {
                "fromPostgresVersion": 15,
                "postgresClusterName": "example",
                "toPostgresVersion": 16
              }
            },
            {
              "apiVersion": "postgres-operator.crunchydata.com/v1beta1",
              "kind": "PostgresCluster",
              "metadata": {
                "name": "example"
              },
              "spec": {
                "backups": {
                  "pgbackrest": {
                    "repos": [
                      {
                        "name": "repo1",
                        "volume": {
                          "volumeClaimSpec": {
                            "accessModes": [
                              "ReadWriteOnce"
                            ],
                            "resources": {
                              "requests": {
                                "storage": "1Gi"
                              }
                            }
                          }
                        }
                      }
                    ]
                  }
                },
                "instances": [
                  {
                    "dataVolumeClaimSpec": {
                      "accessModes": [
                        "ReadWriteOnce"
                      ],
                      "resources": {
                        "requests": {
                          "storage": "1Gi"
                        }
                      }
                    },
                    "replicas": 1
                  }
                ],
                "postgresVersion": 16
              }
            }
          ]
        capabilities: Auto Pilot
        categories: Database
        certified: "true"
        containerImage: registry.connect.redhat.com/crunchydata/postgres-operator@sha256:d81cbd9138ee05f0bad5914def75fd0e9b15ce98c701d7e2baf89abaca64c024
        createdAt: 2019-12-31 19:40Z
        description: Production Postgres Made Easy
        features.operators.openshift.io/cnf: "false"
        features.operators.openshift.io/cni: "false"
        features.operators.openshift.io/csi: "false"
        features.operators.openshift.io/disconnected: "true"
        features.operators.openshift.io/fips-compliant: "false"
        features.operators.openshift.io/proxy-aware: "false"
        features.operators.openshift.io/tls-profiles: "false"
        features.operators.openshift.io/token-auth-aws: "false"
        features.operators.openshift.io/token-auth-azure: "false"
        features.operators.openshift.io/token-auth-gcp: "false"
        olm.operatorGroup: p2-f9b2x
        olm.operatorNamespace: p2
        olm.properties: '[]'
        olm.targetNamespaces: p2
        operatorframework.io/properties: '{"properties":[{"type":"olm.gvk","value":{"group":"postgres-operator.crunchydata.com","kind":"CrunchyBridgeCluster","version":"v1beta1"}},{"type":"olm.gvk","value":{"group":"postgres-operator.crunchydata.com","kind":"PGAdmin","version":"v1beta1"}},{"type":"olm.gvk","value":{"group":"postgres-operator.crunchydata.com","kind":"PGUpgrade","version":"v1beta1"}},{"type":"olm.gvk","value":{"group":"postgres-operator.crunchydata.com","kind":"PostgresCluster","version":"v1beta1"}},{"type":"olm.package","value":{"packageName":"crunchy-postgres-operator","version":"5.7.0"}}]}'
        repository: https://github.com/CrunchyData/postgres-operator
        support: crunchydata.com
      creationTimestamp: null
      labels:
        postgres-operator.crunchydata.com/control-plane: postgres-operator
    spec:
      containers:
      - env:
        - name: REGISTRATION_REQUIRED
          value: "true"
        - name: TOKEN_PATH
          value: /etc/cpk/cpk_token
        - name: REGISTRATION_URL
          value: https://access.crunchydata.com/register-cpk
        - name: RSA_KEY
          value: |-
            -----BEGIN PUBLIC KEY-----
            MIICIjANBgkqhkiG9w0BAQEFAAOCAg8AMIICCgKCAgEA0JWaCc/F+/uV5zJQ7ryN
            uzvO+oGgT7z9uXm11qtKae86H3Z3W4qX+gGPs5LrFg444yDRMLqKzPLwuS2yc4mz
            QxtVbJyBZijbEDVd/knycj6MxFdBkbjxeGeWYT8nuZf4jBnWB48/O+uUnCbIYt8Q
            hUtyJ+KMIXkxrOd4mOgL6dQSCEAIcxBh10ZAucDQIgCn2BrD595uPrvlrrioV/Nq
            P0w0qIaKS785YU75qM4rT8tGeWVMEGst4AaRwfV7ZdVe065TP0hjd9sv8iJkr7En
            /Zym1NXcKbpwoeT3X9E7cVSARPFhZU1mmtL56wq3QLeFxef9TmVva1/Io0mKn4ah
            Uly5jgOpazrXliKJUoOurfMOakkHWfqSd5EfmRTh5nBcNqxtytLdiH0WlCkPSm+Z
            Ue3aY91YwcRnFhImLpbQYD5aVLAryzu+IdfRJa+zcZYSK0N8n9irg6jSrQZBct7z
            OagHUc0n/ZDP/BO8m0jlpJ7jH+N31Z5qFoNSaxf5H1Y/CwByXtzHJ1k2LleYsr9k
            k40nMY4l+SXCe4PmW4zW9uP3ItBWKEI2jFrRJgowQvL0MwtzDhbX9qg4+L9eBFpK
            jpHXr2kgLu4srIyXH6JO5UmE/62mHZh0SuqtOT1GQqWde5RjZyidYkwkAHup/AqA
            P0TPL/poQ6yvI9a0i22TCpcCAwEAAQ==
            -----END PUBLIC KEY-----
        - name: RELATED_IMAGE_PGADMIN
          value: registry.connect.redhat.com/crunchydata/crunchy-pgadmin4@sha256:81bfe6306e66c81db66f9d502fac0dac916ff28d5da9263ec3c80118574c75fc
        - name: RELATED_IMAGE_STANDALONE_PGADMIN
          value: registry.connect.redhat.com/crunchydata/crunchy-pgadmin4@sha256:c7390561edf41f1d566835d8baea4689f64230e8ec6426ac3573079aae3b4ea6
        - name: RELATED_IMAGE_PGBACKREST
          value: registry.connect.redhat.com/crunchydata/crunchy-pgbackrest@sha256:5614fa90c56aac4cd7a9710b7efb24b22e356facbc2e7a52bbeccf5185723199
        - name: RELATED_IMAGE_PGBOUNCER
          value: registry.connect.redhat.com/crunchydata/crunchy-pgbouncer@sha256:9f1f2d4aecde3995d876ffa4e94566a87f8ebe8d1655b392d48601e2bf8d9f50
        - name: RELATED_IMAGE_PGEXPORTER
          value: registry.connect.redhat.com/crunchydata/crunchy-postgres-exporter@sha256:361f6068187551f27e64619ee707f7398001bf016d30eb8b8c38be05e88e1405
        - name: RELATED_IMAGE_PGUPGRADE
          value: registry.connect.redhat.com/crunchydata/crunchy-upgrade@sha256:8c2d2276a72096060a9eebf5abc6331b069936bed5a4f56978843b29100e7b65
        - name: RELATED_IMAGE_POSTGRES_15
          value: registry.connect.redhat.com/crunchydata/crunchy-postgres@sha256:2e5ee1e7f5d6d13547024c4e9134abd726e21026109b095e1f9002aa14ff947e
        - name: RELATED_IMAGE_POSTGRES_16
          value: registry.connect.redhat.com/crunchydata/crunchy-postgres@sha256:282c4c9c3b5c3d67c960585ec6cb947d3a6af981cb48a0083ebebe61cc5b8cc4
        - name: RELATED_IMAGE_POSTGRES_17
          value: registry.connect.redhat.com/crunchydata/crunchy-postgres@sha256:56873bc1a404776d737de7708ae157388a2a855e2bc195ecb0e012ff595bf550
        - name: RELATED_IMAGE_POSTGRES_15_GIS_3.3
          value: registry.connect.redhat.com/crunchydata/crunchy-postgres-gis@sha256:98d6e0eacc6f6398e9465e8bd83b8632b4bdccaa0fd287e34880a36d5d27fc86
        - name: RELATED_IMAGE_POSTGRES_16_GIS_3.3
          value: registry.connect.redhat.com/crunchydata/crunchy-postgres-gis@sha256:cc2881de1811b560f977ad921dbbe215d78a2f8583b3568cc3216bf658ed6008
        - name: RELATED_IMAGE_POSTGRES_16_GIS_3.4
          value: registry.connect.redhat.com/crunchydata/crunchy-postgres-gis@sha256:a6d6a750310228b6fba72af08842eaa8e5d198580983f19ebdd934073bc010af
        - name: RELATED_IMAGE_POSTGRES_17_GIS_3.4
          value: registry.connect.redhat.com/crunchydata/crunchy-postgres-gis@sha256:78896bd959646e99f90df1938e0ba462b4eaa8f23dcefdc668480fbabd421011
        - name: PGO_TARGET_NAMESPACE
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.annotations['olm.targetNamespaces']
        - name: PGO_NAMESPACE
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
        - name: CRUNCHY_DEBUG
          value: "true"
        - name: PGO_INSTALLER
          value: olm
        - name: PGO_INSTALLER_ORIGIN
          value: operatorhub-certified
        - name: OPERATOR_CONDITION_NAME
          value: postgresoperator.v5.7.0
        image: registry.connect.redhat.com/crunchydata/postgres-operator@sha256:d81cbd9138ee05f0bad5914def75fd0e9b15ce98c701d7e2baf89abaca64c024
        imagePullPolicy: IfNotPresent
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: /readyz
            port: 8081
            scheme: HTTP
          initialDelaySeconds: 15
          periodSeconds: 20
          successThreshold: 1
          timeoutSeconds: 1
        name: operator
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /healthz
            port: 8081
            scheme: HTTP
          initialDelaySeconds: 5
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        resources: {}
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - ALL
          readOnlyRootFilesystem: true
          runAsNonRoot: true
          seccompProfile:
            type: RuntimeDefault
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /etc/cpk
          name: cpk-registration-volume
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      serviceAccount: pgo
      serviceAccountName: pgo
      terminationGracePeriodSeconds: 30
      volumes:
      - name: cpk-registration-volume
        secret:
          defaultMode: 420
          optional: true
          secretName: cpk-registration
