apiVersion: batch/v1
kind: Job
metadata:
  annotations:
    batch.kubernetes.io/job-tracking: ""
    postgres-operator.crunchydata.com/pgbackrest-hash: 65bb57b6b5
  labels:
    postgres-operator.crunchydata.com/cluster: pyas2postgres
    postgres-operator.crunchydata.com/pgbackrest: ""
    postgres-operator.crunchydata.com/pgbackrest-backup: replica-create
    postgres-operator.crunchydata.com/pgbackrest-repo: repo1
  name: pyas2postgres-backup-p2fx
  ownerReferences:
  - apiVersion: postgres-operator.crunchydata.com/v1beta1
    blockOwnerDeletion: true
    controller: true
    kind: PostgresCluster
    name: pyas2postgres
    uid: 61cd6c40-24f8-4020-8bc3-df9efa28a6b8
spec:
  backoffLimit: 6
  completionMode: NonIndexed
  completions: 1
  parallelism: 1
  selector:
    matchLabels:
      batch.kubernetes.io/controller-uid: 3ee0687c-5e05-436b-80a8-0b0f262c6c83
  suspend: false
  template:
    metadata:
      annotations:
        postgres-operator.crunchydata.com/pgbackrest-hash: 65bb57b6b5
      creationTimestamp: null
      labels:
        batch.kubernetes.io/controller-uid: 3ee0687c-5e05-436b-80a8-0b0f262c6c83
        batch.kubernetes.io/job-name: pyas2postgres-backup-p2fx
        controller-uid: 3ee0687c-5e05-436b-80a8-0b0f262c6c83
        job-name: pyas2postgres-backup-p2fx
        postgres-operator.crunchydata.com/cluster: pyas2postgres
        postgres-operator.crunchydata.com/pgbackrest: ""
        postgres-operator.crunchydata.com/pgbackrest-backup: replica-create
        postgres-operator.crunchydata.com/pgbackrest-repo: repo1
    spec:
      containers:
      - command:
        - /opt/crunchy/bin/pgbackrest
        env:
        - name: COMMAND
          value: backup
        - name: COMMAND_OPTS
          value: --stanza=db --repo=1
        - name: COMPARE_HASH
          value: "true"
        - name: CONTAINER
          value: pgbackrest
        - name: NAMESPACE
          value: p2
        - name: SELECTOR
          value: postgres-operator.crunchydata.com/cluster=pyas2postgres,postgres-operator.crunchydata.com/pgbackrest=,postgres-operator.crunchydata.com/pgbackrest-dedicated=
        image: registry.connect.redhat.com/crunchydata/crunchy-pgbackrest@sha256:5614fa90c56aac4cd7a9710b7efb24b22e356facbc2e7a52bbeccf5185723199
        imagePullPolicy: IfNotPresent
        name: pgbackrest
        resources: {}
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - ALL
          privileged: false
          readOnlyRootFilesystem: true
          runAsNonRoot: true
          seccompProfile:
            type: RuntimeDefault
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /etc/pgbackrest/conf.d
          name: pgbackrest-config
          readOnly: true
      dnsPolicy: ClusterFirst
      enableServiceLinks: false
      restartPolicy: Never
      schedulerName: default-scheduler
      securityContext:
        fsGroupChangePolicy: OnRootMismatch
      serviceAccount: pyas2postgres-pgbackrest
      serviceAccountName: pyas2postgres-pgbackrest
      terminationGracePeriodSeconds: 30
      volumes:
      - name: pgbackrest-config
        projected:
          defaultMode: 420
          sources:
          - configMap:
              items:
              - key: pgbackrest_repo.conf
                path: pgbackrest_repo.conf
              - key: config-hash
                path: config-hash
              - key: pgbackrest-server.conf
                path: ~postgres-operator_server.conf
              name: pyas2postgres-pgbackrest-config
          - secret:
              items:
              - key: pgbackrest.ca-roots
                path: ~postgres-operator/tls-ca.crt
              - key: pgbackrest-client.crt
                path: ~postgres-operator/client-tls.crt
              - key: pgbackrest-client.key
                mode: 384
                path: ~postgres-operator/client-tls.key
              name: pyas2postgres-pgbackrest
