apiVersion: operators.coreos.com/v2
kind: OperatorCondition
metadata:
  labels:
    operators.coreos.com/crunchy-postgres-operator.p2: ""
  name: postgresoperator.v5.7.0
  ownerReferences:
  - apiVersion: operators.coreos.com/v1alpha1
    blockOwnerDeletion: false
    controller: true
    kind: ClusterServiceVersion
    name: postgresoperator.v5.7.0
    uid: eaddaa29-e2ae-4b95-94b6-45d65cc50655
spec:
  deployments:
  - pgo
  serviceAccounts:
  - pgo
