apiVersion: postgres-operator.crunchydata.com/v1beta1
kind: PostgresCluster
metadata:
  finalizers:
  - postgres-operator.crunchydata.com/finalizer
  name: pyas2postgres
spec:
  backups:
    pgbackrest:
      repos:
      - name: repo1
        volume:
          volumeClaimSpec:
            accessModes:
            - ReadWriteOnce
            resources:
              requests:
                storage: 10Gi
  instances:
  - dataVolumeClaimSpec:
      accessModes:
      - ReadWriteOnce
      resources:
        requests:
          storage: 10Gi
    name: instance1
    replicas: 1
  port: 5432
  postgresVersion: 16
  users:
  - databases:
    - pyas2db
    name: pyas2dbuser
