apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: postgresoperator.v5.7.0
  ownerReferences:
  - apiVersion: operators.coreos.com/v2
    blockOwnerDeletion: false
    controller: true
    kind: OperatorCondition
    name: postgresoperator.v5.7.0
    uid: 64fe03b7-ab99-4279-be31-978a815c7a95
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: postgresoperator.v5.7.0
subjects:
- kind: ServiceAccount
  name: pgo
