apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: postgresoperator.v5.7.0
  ownerReferences:
  - apiVersion: operators.coreos.com/v2
    blockOwnerDeletion: false
    controller: true
    kind: OperatorCondition
    name: postgresoperator.v5.7.0
    uid: 64fe03b7-ab99-4279-be31-978a815c7a95
rules:
- apiGroups:
  - operators.coreos.com
  resourceNames:
  - postgresoperator.v5.7.0
  resources:
  - operatorconditions
  verbs:
  - get
  - update
  - patch
