apiVersion: authorization.openshift.io/v1
kind: Role
metadata:
  labels:
    postgres-operator.crunchydata.com/cluster: pyas2postgres
  name: pyas2postgres-instance
  ownerReferences:
  - apiVersion: postgres-operator.crunchydata.com/v1beta1
    blockOwnerDeletion: true
    controller: true
    kind: PostgresCluster
    name: pyas2postgres
    uid: 61cd6c40-24f8-4020-8bc3-df9efa28a6b8
rules:
- apiGroups:
  - ""
  attributeRestrictions: null
  resources:
  - endpoints
  verbs:
  - create
  - deletecollection
  - get
  - list
  - patch
  - watch
- apiGroups:
  - ""
  attributeRestrictions: null
  resources:
  - endpoints/restricted
  verbs:
  - create
- apiGroups:
  - ""
  attributeRestrictions: null
  resources:
  - pods
  verbs:
  - get
  - list
  - patch
  - watch
- apiGroups:
  - ""
  attributeRestrictions: null
  resources:
  - services
  verbs:
  - create
