apiVersion: v1
imagePullSecrets:
- name: pyas2postgres-pgbackrest-dockercfg-b47bk
kind: ServiceAccount
metadata:
  labels:
    postgres-operator.crunchydata.com/cluster: pyas2postgres
    postgres-operator.crunchydata.com/pgbackrest: ""
  name: pyas2postgres-pgbackrest
  ownerReferences:
  - apiVersion: postgres-operator.crunchydata.com/v1beta1
    blockOwnerDeletion: true
    controller: true
    kind: PostgresCluster
    name: pyas2postgres
    uid: 61cd6c40-24f8-4020-8bc3-df9efa28a6b8
secrets:
- name: pyas2postgres-pgbackrest-dockercfg-b47bk
