apiVersion: v1
kind: Service
metadata:
  labels:
    postgres-operator.crunchydata.com/cluster: pyas2postgres
  name: pyas2postgres-pods
spec:
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  publishNotReadyAddresses: true
  selector:
    postgres-operator.crunchydata.com/cluster: pyas2postgres
  sessionAffinity: None
  type: ClusterIP
