apiVersion: v1
imagePullSecrets:
- name: pgo-dockercfg-bcslj
kind: ServiceAccount
metadata:
  labels:
    operators.coreos.com/crunchy-postgres-operator.p2: ""
  name: pgo
  ownerReferences:
  - apiVersion: operators.coreos.com/v1alpha1
    blockOwnerDeletion: false
    controller: false
    kind: ClusterServiceVersion
    name: postgresoperator.v5.7.0
    uid: eaddaa29-e2ae-4b95-94b6-45d65cc50655
secrets:
- name: pgo-dockercfg-bcslj
