apiVersion: v1
kind: Service
metadata:
  labels:
    postgres-operator.crunchydata.com/cluster: pyas2postgres
    postgres-operator.crunchydata.com/patroni: pyas2postgres-ha
  name: pyas2postgres-ha-config
spec:
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  - IPv6
  ipFamilyPolicy: RequireDualStack
  sessionAffinity: None
  type: ClusterIP
